name: CI
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'runnerID'
        default: 'john-doe'
        required: false
        type: string
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: testVar
      run: echo $Env:NGROK_AUTH_TOKEN
    - run: echo $Env:WIREGUARD > C:/vpn.conf
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Wireguard
      run: Invoke-WebRequest "https://download.wireguard.com/windows-client/wireguard-installer.exe" -OutFile wireguard.exe
    - run: Start-Process -FilePath wireguard.exe -ArgumentList "/install /quiet /norestart" -Wait
    - name: frenchLayout
      run: |
          dism /online /add-capability /capabilityname:Language.Basic~~~fr-FR~0.0.1.0
      shell: powershell
    - name: MapDrive
      run: $net = new-object -ComObject WScript.Network
    - run: $net.MapNetworkDrive("r:", "\\192.168.1.254\Main", $false, "lamas", "dfujbx123")
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp --region in 3389 --log=stdout
